name: Deploy to Staging
on: 
  push:
    branches:
      - "stage"

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    - name: Deploying everything to staging cluster
      
      steps:
      - name: SSH into server
        run: |
          echo ${{ secrets.SSH_STG_PRIVATE_KEY }} &> ~/ssh_key
          ssh -i ~/ssh_key root@13.233.126.210
          cd cicd-monorepo-deploy && git pull
          pnpm install
          pnpm run build
          pm2 resstart fe-server
          pm2 restart http-server
          pm2 restart ws-server